// Maps each image slot (by its label) to a file in /public/images.
// Slots without an entry still render the labelled placeholder.
export const mediaMap: Record<string, string> = {
  "Boxer training in gym": "home-hero",
  "Session preview": "session-preview",
  "Human Trainer coaching a boxer": "human-trainer",
  "Simulated AI Trainer robot": "ai-trainer",
  "VR/AR/XR immersive training": "xr",
  "Live event crowd": "events-crowd",
  "Partnership team meeting": "partnership",
  "Group training session": "training-hero",
  "Strength foundations": "plan-strength",
  "Movement + conditioning": "plan-mma",
  "Boxing foundations": "plan-boxing",
  "Control + mobility": "plan-taekwondo",
  "Trainer assisting seated session": "adaptive-seated",
  "Boxer and simulated AI Trainer robot": "humanai-hero",
  "Human Trainer coaching, laptop reviewing form": "human-coaching",
  "AI Trainer robot demonstration": "ai-demo",
  "Posture analysis overlay": "posture-overlay",
  "XR headset with room-aware overlay": "xr-guidance",
  "Arena crowd and boxing ring": "events-hero",
  "Precision Night": "event-boxing",
  "Movement Lab Live": "event-mma",
  "Forms In Focus": "event-taekwondo",
  "Adaptive Strength Forum": "event-conditioning",
  "Boxer ring walk under lights": "event-featured",
  "Group training circle": "membership-hero",
  "Desktop, tablet, phone and headset on a desk": "devices-hero",
  "Training synced across devices": "devices-sync",
  "Strategy and partnership meeting": "partnerships-hero",
  "Accessible tech innovation lab": "partnerships-lab",
  "Team celebrating after training": "about-hero",
  "Athlete wrapping hands before training": "about-mission",
  "Trainer checking equipment with athlete": "safety-hero",
  "Athlete pausing to hydrate": "safety-pause",
  "Adaptive strength training session": "accessibility-hero",
  "Trainer assisting wheelchair user": "accessibility-adaptive",
};
